---
title: "K-Means Clustering"
author: "Kyle Knuth"
date: 'today'
format:
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Introduction

### What is "method"?

### Related work

#### Article Summary 1

This article is about using k means clustering to look for defects on
imported fruit, since it is time consuming to do it manually. The
researchers’ goal is to segment an image of a fruit based off color
using k-means clustering to determine if the fruit has “gone bad”.
First, the authors explain how k-means clustering works and how it is
applied. For example, the data is partitioned into clusters which have
common traits and each cluster has a cluster center which starts from
seed points. Then, k-means clustering calculates the distance between
each data point and each cluster center and assigns the data point to
the closest center. In order to apply this to their current research
question, the images of the fruit are used and the pixels are clustered
by color and spatial features. The clustered pixels are then combined to
specific areas. The distribution of the intensity values is calculated
and then using ‘k’ random intensities the centroids are set. The image
points are clustered by distance of intensity values to the centroid. A
new centroid is calculated and the previous two steps are repeated until
the labels of the clusters no longer change. In order to segment the
colors of the fruit, an image of the fruit was input and transformed
from RGB to L\*a\*b\*. The authors decided to use L\*a\*b\*  because of
the luminosity option and because all the color info is only in the a
and b layers. This made segmenting the colors easier. The colors were
classified in the a\*b\* layers and Euclidean distance was used to
measure difference between colors. Each pixel in the image was labeled
from k-means. K-means then computed the index corresponding to each
cluster for each pixel and the pixel is labeled with a cluster index.
Different images of the same fruit were then produced based on each
cluster. The results in the paper were very interesting. They were able
to clearly separate a single image of a fruit into multiple based off
the coloring of that fruit. For example, they used an apple with scab
disease and were able to use k-means clustering to separate out the
diseased part of the apple. After some brief experimentation, they
decided it was best to separate the images into 3 or 4 clusters. A
limitation in this study is that too many or too few clusters would
provide a lot of variability in detecting the “bad” part of the fruit
and produce error. [@dubey2013infected]

#### Article Summary 2

The goal of the author was to use a more objective method to assess
aquifer contamination. The normal method was to use Depth to water
table, net Recharge, Aquifer media, Soil media, Topography, Impact
of vadose zone and hydraulic Conductivity (DRASTIC). The original
problem was that selecting weights for the DRASTIC method was
subjective. The author uses k means clustering to create a vulnerability
map which doesn’t use fixed weights and uses 4 of the original 7 DRASTIC
factors (DRIC). The author chose to do an analysis on an aquifer in Iran
and made separate vulnerability maps using DRASTIC and k means
clustering. The method of this analysis included creating a
vulnerability map with DRASTIC, performing Principal Component Analysis
to reduce the number of features, k means clustering was then used to
acquire clusters from the new dataset and in turn was used to create a
second vulnerability map. Lastly, the water quality of the aquifer was
analyzed by collecting samples over the area the aquifer encompassed and
both vulnerability maps were statistically compared to the water
quality. The author then explains how k means clustering takes an nxd
matrix and creates clusters in which data points are assigned. The
assignment begins randomly but then is rearranged to where each data
point is assigned to the nearest cluster. Using the Davie-Bouldin Index,
it was found the best number of clusters was 5. Using Pearson’s
correlation coefficient to compare both vulnerability maps to the actual
water quality observations, it was found that the k means clustering
method was better than the DRASTIC method. The author also found the
p-value from Student's t-test to show there was a significant
difference. The authors state that there could be a limitition in the
methodology behind k-means clustering when used on even more complex
aquifers in future analysis. [@javadi2017classification]

#### Article Summary 3

The main goal of the authors is to use k-means clustering on
pharmacokinetic parameters to predict chemotherapy response to bladder
cancer. K-means clustering was used to alleviate the limitations in
analyzing and interpreting the data gained from examining the
effectiveness of therapeutic treatments. The data was segmented into
clusters based off the distance of each individual data point to the
cluster center. They decided to use three clusters and they determined
the efficacy of the treatment by observing the changes of the cluster
volume from the start of the treatment to the halfway point. They based
each cluster off the amplitude and rate of microcirculation in the tumor
tissue. Cluster one had a low amplitude and low rate, cluster two had a
high amplitude and low rate, and cluster three had a high rate and low
amplitude. When comparing the clusters of responders (responsive bladder
cancer) and nonresponders (nonresponsive bladder cancer) of the
treatment, responders had larger volume reduction in clusters one and
three compared to cluster two. In nonresponders, cluster two had a
volume increase. By observing the changes in volume, the authors were
able to measure the tumor size before and after chemotherapy. They
measured the cluster volume fractions before and halfway through
treatment and found a 9% change in cluster one, a 17% change in cluster
two, and a 5% change in cluster three in responders. In nonrepsonders,
there was a 12 % change in cluster one, a 15% change in cluster two, and
a 3% change in cluster three. Overall, k-means clustering was able to
visualize the tumor from MRI’s, as well as show the response of
chemotherapy. By using k-means clustering, they were able to use the
clusters as biomarkers to identify the effectiveness of chemo, as well
as an indication of future tumor response to chemotherapy. Some
limitations in this study are that the sample size for nonresponders was
small and motion correction wasn’t used in the analysis of the MRI data.

[@nguyen2015prediction]

#### Article Summary 4

In this article, the authors’ wanted to identify patterns of change in
skin pores using k-means clustering. Using three-dimensional
measurements, the authors’ looked for patterns of how pores change due
to age. Their measurements came from 101 Korean women’s cheeks. The skin
pores were grouped into five clusters based off the size, density, and
elongation of the pores. The pores were segmented by projecting the
three-dimensional surface into a two dimensional plane (depth map). The
intensities of the pixels corresponds to the z-coordinate. From there,
the skin pores were segmented. Within each segmentation, the area and
elongation was computed. The average pore size, pore elongation, and
pore densities were used as variables. The Elbow method, which was used
to find the best number of clusters in this study, consists of plotting
the sum of squared error versus K numbers and wherever the slope
plateaued it indicated a potential cluster. The pores were clustered
into the five groups as follows: a few pores are detected and they are
small, the pores are larger and more detectable, the pores are even
larger and more detectable, then for the last two clusters the pores
increase in size and elongation but become harder to detect. The mean
age of the first cluster is 10.1, the mean age of the second cluster is
31.2, the mean age of the third is 35.8, the mean age of the fourth is
48.6, and the mean age of the fifth cluster is 55.8. According to the
authors’, the change in pores from clusters one and two may be due to
puberty. The results of this study show that pores become larger and
more elongated as one ages indicating that pores play a role in the
appearance of wrinkles and aging skin. Some limitations in this study
are that data regarding the patients lifestyles or health related
conditions which might explain the status of their pores was not
available and the detection of connected pores needed to be improved.
The connected pores cause significant increases in elongation.

[@lee2022identifying]

#### Article Summary 5

In the article, “K‐means cluster analysis of characteristic patterns of
allergen in different ages: Real life study” by Zhao et. al., the
authors’ goal was to use k-means clustering to cluster different age
groups based off the severity of allergens. They wanted to see the
relationship age had on potentially reducing the severity of allergens.
An allergen specific immunoglobulin test was used to test 17 of the most
common allergens such as dog, cat, penicillin, and shellfish. The
allergen severity was partitioned into 7 grades with ranges between 0
and greater than 100 kU/L and each grade was assigned a number from 0 to
6. The authors then explain that k-means clustering is unsupervised
machine learning, and it finds similar groups of unlabeled data. In this
case, k-means clustering was used to cluster age groups according to
allergen sensitivity. Their implementation of k-means clustering
consisted of randomly extracting k-number of data objects and computing
the centroids. Then the data is put into clusters by reducing the
distance of the centroids of each cluster. Finally, the centroids are
recalculated according to the previous step over and over until the
clusters come together. The k-means clustering analysis ended up
creating the following 5 different age groups: 1-17, 18-36, 37-52,
53-69, and 70-100. Interestingly, the incidence of both atopy and
aeroallergens decreased as the age increased. It went from 59.79% to
37.62% from the first age group to the last age group. Concerning food
allergens, the incidence was all over the place between the age groups
depending on the specific food. For example, seafood sensitivity was
increased in older age groups. Another interesting result was the
incidence of poly-sensitization decreased with increasing age as well.
It was also observed that in all age groups, except 37-52, the incidence
of atopy was higher in males than females. In addition, it was found
that dust mite sensitization had the highest incidence in patients up to
age 52. Limitations of this study are that the data came from a single
area and their statistical methods assume there is a cause-effect
relationship of the risk factors and atopy. [@zhao2023k]

#### Article Summary 6

In the article “Determining County-Level Counterfactuals for Evaluation
of Population Health Interventions: A Novel Application of K-Means
Cluster Analysis” by Strutz, et. al., k-means clustering was used to
find county-level counterfactuals. The goal was to find a counterfactual
group that was very alike to the group which was the target of
intervention (Kent County) so they could estimate the group
randomization. Their analysis is based off the 83 counties in Michigan
and chose population composition, social and economic factors, health
care access, health outcomes, health behaviors, and physical environment
as categories to gather features. A total of 35 features was gathered
from these categories. The method of k-means clustering was used to find
comparison counties that were put in the same cluster as intervention
counties. Their method of selecting an optimal number of clusters
consisted of using a scree plot to visualize the curve created from
"within sum of squares". They ran one analysis in which the features
were standardized and another analysis in which the features were not
standardized. The non-standardized analysis produced an optimal number
of clusters of 4 and the standardized version produced no clear optimal
number of clusters. Due to this issue, they tried different
standardizations and distance methods. Due to a previous study, they
used Kent County in Michigan as the object of comparison and clustering.
When using Euclidean distance, it was found that the three most similar
counties to Kent County using non-standardized features were Macomb,
Oakland, and Genesee. When using standardized features, it was Ingham,
Kalamazoo, and Muskegon counties. According to the authors, k-means
clustering identified 1-3 comparison counties using non-standardized
features. Based on their analysis, it was found that the selection of
their counties using a single distance measure was sensitive to their
choices of standardization and measure of distance. Limitations of this
study are that the data chosen was not optimal, the presence of masking
variables, a counterfactual community being compared at baseline was not
comparable later in the study, and the presence of variables of high
variability. This article really showcases the limitations of k-means
clustering and what type of data is best used for
it.[@strutz2022determining]

## Methods

## Analysis and Results

### Data and Visualization

A study was conducted to determine how...

### Statistical Modeling

### Conclusion

## References
